from Configure import conftest
from TaskGen import feature, extension, before, after
import Options

sources = [
]

pyste_module = "libfinitedifference"
pyste_sources = [
	"src/pyste/finitedifferencehelper.pyste",
]

def set_options(opt):
	pass

def configure(conf):
	print("-----> Configuring finitedifference")


def build(bld):
	if bld.is_module_enabled("finitedifference"):
		tskgen = bld.new_task_gen(
			features="pyprop pyste compile link",
			source=sources,
			local_libraries="core/libcore",
			pyste_files=pyste_sources,
			pyste_module=pyste_module,
			pyste_force=False,
			pyprop_path="../../../../",
		)

