import os
import Options

sources = [
]

pyste_module = "libhydrogen1d"
pyste_sources = [
	"wrapper.pyste",
]

def set_options(opt):
	#options from pyprop_waf
	opt.tool_options("pyprop_waf", tooldir="../../../pyprop/build")
	

def configure(conf):
	print("---> Configuring hydrogen 1D")


def build(bld):
	tskgen = bld.new_task_gen(
		features="pyprop pyste compile link",
		source=sources,
		local_libraries="core/libcore",
		pyste_files=pyste_sources,
		pyste_module=pyste_module,
		pyste_force=False,
		pyprop_path="../../..",
	)

# vim: syntax=python
