#include "bsplinegridrepresentation.h"

namespace BSpline
{

void BSplineGridRepresentation::ApplyConfigSection(const ConfigSection &config)
{
	/* 
	 * We don't do anything here, since all settings&data
	 * are copied from the bspline-object generated by 
	 * BsplineRepresentation
	 */
}

void BSplineGridRepresentation::SetupRepresentation(BSpline::Ptr p)
{
	// Local pointer to bspline object
	BSplineObject = p;

	// Get grid and weights from bspline object
	Grid.reference( BSplineObject->GetQuadratureGridGlobal().copy() );
	Weights.reference( BSplineObject->GetQuadratureWeightsGlobal().copy() );
	
	//blitz::Array<double, 1> grid = BSplineObject->GetQuadratureGridGlobal();
	//blitz::Array<double, 1> weights = BSplineObject->GetQuadratureWeightsGlobal();

	// Resize grid and weight vectors
	//Grid.resize(grid.shape());
	//Weights.resize(weights.shape());
	//Grid = grid;
	//Weights = weights;


}	

} //namespace

