#include "bsplinegridrepresentation.h"

namespace BSpline
{

void BSplineGridRepresentation::ApplyConfigSection(const ConfigSection &config)
{
	/* 
	 * We don't do anything here, since all settings&data
	 * are copied from the bspline-object generated by 
	 * BsplineRepresentation
	 */
}

void BSplineGridRepresentation::SetupRepresentation(BSpline::Ptr p)
{
	// Local pointer to bspline object
	BSplineObject = p;

	// Get grid and weights from bspline object
	Grid.reference( BSplineObject->GetQuadratureGridGlobal().copy() );
	Weights.reference( BSplineObject->GetQuadratureWeightsGlobal().copy() );

	//cout << "Grid = " << Grid << endl;
	//cout << "Weights = " << Weights << endl;
	//cout << "Full Shape = " << GetFullShape() << endl;
}	

} //namespace

