from Configure import conftest
from TaskGen import feature, extension, before, after
import Options

sources = [
	"src/combinedpropagator/reducedsphericaltools.cpp",
	"src/combinedpropagator/reducedsphericaltransform.cpp",
	"src/representation/thetarepresentation.cpp",
]

pyste_module = "libreducedspherical"
pyste_sources = [
	"src/pyste/reducedsphericalkineticpotential.pyste",
	"src/pyste/reducedsphericalrepresentation.pyste",
	"src/pyste/reducedsphericaltransform.pyste",
	"src/pyste/tensorpotential_basis_reducedspherical.pyste",
]

def set_options(opt):
	pass

def configure(conf):
	print("-----> Configuring reducedspherical")


def build(bld):
	tskgen = bld.new_task_gen(
		features="pyprop pyste compile link",
		source=sources,
		local_libraries="core/libcore",
		pyste_files=pyste_sources,
		pyste_module=pyste_module,
		pyste_force=False,
		pyprop_path="../../../../",
	)

