#------------------------------------------------------------------------------------
#                       Name generators
#------------------------------------------------------------------------------------
INFO_Eigenvalues = "eigenvalues"

def GetEigenvectorFilename(**args):
	gridPostfix = GetGridPostfix(**args)
	filenamebase = "eigenstates/boundstates" + "_".join(gridPostfix) + ".h5"
	return filenamebase

def GetEigenvectorDatasetName(eigenvectorIndex):
	return "Eigenvector_%i" % eigenvectorIndex 


def GetEigenvectorDatasetPath(eigenvectorIndex):
	return "/Eig/%s" % GetEigenvectorDatasetName(eigenvectorIndex) 


def GetEigenstateFileInfo(filename, infoId):
	if infoId == "eigenvalues":
		#Get energies
		f = tables.openFile(filename, "r")
		try:
			eigenvalues = f.root.Eig.Eigenvalues[:]
		finally:
			f.close()
		return eigenvalues

	else:
		conf = GetEigenstateFileConfig(filename)
		return GetConfigInfo(conf, infoId)

#------------------------------------------------------------------------------------
#                     Finding, saving and loading functions
#------------------------------------------------------------------------------------
def FindAndSaveEigenvectors(**args):
	"""
	Find eigenvectors using Piram, and save them to a HDF5 file with
	name generated by 'GetEigenvectorFilename'
	"""
	#Find some bound states
	solver = FindEigenvalues(**args)

	#...and store 'em
	fname = GetEigenvectorFilename(**args)
	SaveEigenvectors(fname, solver)


def FindAndSaveEigenvectorsAnasazi(shift, **args):
	"""
	Find eigenvectors using Anasazi, and save them to a HDF5 file with
	name generated by 'GetEigenvectorFilename'
	"""
	#Find some bound states
	solver, eigenvalues = FindEigenvaluesDavidsonAnasazi(shift, **args)

	#...and store 'em
	fname = GetEigenvectorFilename(**args)
	SaveEigenvectors(fname, solver)


def SaveEigenvectors(filename, solver):
	#Get eigenvalues
	prop = solver.BaseProblem
	E = array(solver.GetEigenvalues())

	#remove file if it exists
	try:
		if os.path.exists(filename):
			if pyprop.ProcId == 0:
				os.remove(filename)
	except:
		PrintOut("Could not remove %s (%s)" % (filename, sys.exc_info()[1]))

	#Store eigenvalues and eigenvectors
	PrintOut("Now storing eigenvectors...")
	for i in range(len(E)):
		solver.SetEigenvector(prop.psi, i)
		prop.SaveWavefunctionHDF(filename, GetEigenvectorDatasetPath(i))

	if pyprop.ProcId == 0:
		RemoveExistingDataset(filename, "/Eig/Eigenvalues")
		h5file = tables.openFile(filename, "r+")
		try:
			myGroup = h5file.getNode("/Eig")
			h5file.createArray(myGroup, "Eigenvalues", E)

			#Store config
			myGroup._v_attrs.configObject = prop.Config.cfgObj
			
		finally:
			h5file.close()


#------------------------------------------------------------------------------------
#                     Find eigenpairs using Anasazi
#------------------------------------------------------------------------------------
from pyprop.core import IfpackRadialPreconditioner_2, AnasaziSolver_2
from pyprop import AnasaziSolver
pyprop.ProjectNamespace = globals()


def FindEigenvaluesDavidsonAnasazi(shift, **args):
	"""
	Calculates eigenvalues and eigenvectors for **args around shift
	by using Block-Davidson algorithm from Anasazi
	"""
	
	#Setup Problem
	prop = SetupProblem(silent=True, eigenvalueShift=shift, disablePreconditioner=False, **args)

	#Setup preconditioner
	preconditionerName = prop.Config.Propagation.preconditioner
	Preconditioner = None
	if preconditionerName:
		preconditionerSection = prop.Config.GetSection(preconditionerName)
		Preconditioner = preconditionerSection.type(prop.psi)
		preconditionerSection.Apply(Preconditioner)
		Preconditioner.SetHamiltonianScaling(1.0)
		Preconditioner.SetOverlapScaling(-shift)
		Preconditioner.Setup(prop.Propagator)

	solver = AnasaziSolver(prop, preconditioner=Preconditioner)
	solver.Solve()
	
	#Get the converged eigenvalues
	eigenvalues = solver.Solver.GetEigenvalues().copy()
	PrintOut("eigenvalues = %s" % eigenvalues)

	return solver, eigenvalues
