import os.path
import os

subdirs = "discretizations redirect"

def set_options(opt):
	print('---> Options from modules')
	opt.sub_options(subdirs)

def configure(conf):
	print('---> Configuring modules')
	conf.sub_config(subdirs)

def build(bld):
	bld.add_subdirs(subdirs) 



