from Configure import conftest
from TaskGen import feature, extension, before, after
import Options

sources = [
	"src/gmres/gmreswrapper.cpp",
	"src/pamp/pampwrapper.cpp",
	"src/piram/piramsolver.cpp",
]

pyste_module = "libkrylov"
pyste_sources = [
	"src/pyste/gmres.pyste",
	"src/pyste/pamp.pyste",
	"src/pyste/piram.pyste",
]

def set_options(opt):
	pass

def configure(conf):
	print("-----> Configuring krylov")


def build(bld):
	if bld.is_module_enabled("krylov"):
		tskgen = bld.new_task_gen(
			features="pyprop pyste compile link",
			source=sources,
			local_libraries="core/libcore",
			pyste_files=pyste_sources,
			pyste_module=pyste_module,
			pyste_force=False,
			pyprop_path="../../../../",
		)

