from Configure import conftest
from TaskGen import feature, extension, before, after
import Options

sources = [
	"src/redirect.cpp",
]

pyste_module = "libredirect"
pyste_sources = [
	"src/wrapper.pyste",          
]

def set_options(opt):
	pass

def configure(conf):
	print("----> Configuring libredirect")


def build(bld):
	if Options.options.EnableModuleRedirect:
		tskgen = bld.new_task_gen(
			features="pyprop pyste compile link",
			source=sources,
			pyste_files=pyste_sources,
			pyste_module=pyste_module,
			pyste_force=True,
			pyprop_path="../../../",
		)


	

