from Configure import conftest
from TaskGen import feature, extension, before, after
import Options

sources = [
	"bspline.cpp",
	"combinedpropagator/bsplinepropagator.cpp",
	"combinedpropagator/bsplinetransform.cpp",
	"representation/bsplinerepresentation.cpp",
	"representation/bsplinegridrepresentation.cpp",
]

pyste_module = "libbspline"
pyste_sources = [
	"pyste/bsplinemain.pyste",
	"pyste/bsplinetensorpotential.pyste",
	"pyste/bsplinerepresentation.pyste",
	"pyste/bsplinetransform.pyste",
]

def set_options(opt):
	pass

def configure(conf):
	print("-----> Configuring bspline")


def build(bld):
	if Options.options.EnableModuleBSpline:
		tskgen = bld.new_task_gen(
			features="pyprop pyste compile link",
			source=sources,
			local_libraries="core/libcore",
			pyste_files=pyste_sources,
			pyste_module=pyste_module,
			pyste_force=True,
			pyprop_path="../../../../",
		)

