import os.path
import os
import Options

def set_options(opt):
	print('--> Options from pyprop')
	opt.add_option("--enable-modules", action="store", dest="EnableModules", default="")
	opt.add_option("--disable-modules", action="store", dest="DisableModules", default="")
	opt.sub_options("core modules")

def configure(conf):
	print('--> Configuring pyprop')
	if Options.options.EnableCore:
		conf.sub_config("core")

	if Options.options.EnableModules:
		conf.sub_config("modules")

def build(bld):
	if bld.is_module_enabled("core"):
		bld.add_group("core")
		bld.add_subdirs("core")

	bld.add_group("modules")
	bld.add_subdirs("modules")



